### ISSUE TITLE
Largeur des liens

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm-portail#64]
fixer la largeur des liens dans le menu:

<img width="1293" alt="Capture d’écran 2020-05-26 à 15 41 09" src="https://user-images.githubusercontent.com/47273014/82907796-600af480-9f67-11ea-9e69-8ced569a4bca.png">

**Comment by palimpZest** [comment]
Fixed with commit # https://github.com/SocialGouv/emjpm-portail/pull/69/commits/de4f6e4a48fc8cbbcb152199f6f0840ba503a273
