### ISSUE TITLE
CSS sur le menu item actif

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm-portail#65]
Le trait n'apparait pas sur le menu actif

<img width="1293" alt="Capture d’écran 2020-05-26 à 15 41 09" src="https://user-images.githubusercontent.com/47273014/82907919-8761c180-9f67-11ea-9f4a-0ccdd9583f46.png">

**Comment by palimpZest** [comment]
Fixed with commit # https://github.com/SocialGouv/emjpm-portail/pull/69/commits/14bd62539e89142dfc1c42685f8a22e3705c7a8f
