### ISSUE TITLE
Eteindre la zone cliquable

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm-portail#66]
Sur lien n'est que sur le texte. Il faudarait élargir la zone cliquable:

<img width="225" alt="Capture d’écran 2020-05-26 à 15 43 11" src="https://user-images.githubusercontent.com/47273014/82908036-b1b37f00-9f67-11ea-8705-f44aae57fd46.png">

**Comment by palimpZest** [comment]
Fixed with commit # https://github.com/SocialGouv/emjpm-portail/pull/69/commits/14bd62539e89142dfc1c42685f8a22e3705c7a8f
